"use client";
import {useEffect,useMemo,useState} from "react";
type Choice={value:string;label:string;image?:string};type Step={id:string;code:string;title:string;type:string;required?:boolean;options?:Choice[]};type Measure={code:string;name:string;unit:string;min:number;max:number;step:number};
type Config={buttonLabel:string;pricingMode:"none";steps:Step[];measurementFields:Measure[]};
type Template={id:string;code:string;name:string;category:string;status:"draft"|"published";version:number;config:Config;updatedAt:string};
type Binding={id:string;shopifyProductId:string;productTitle:string;productHandle:string;templateId:string;publishedVersion:number|null;updatedAt?:string};
type Version={id:string;templateId:string;version:number;config:Config;publishedAt:string};type View="templates"|"products"|"versions";
const starter:Config={buttonLabel:"开始定制",pricingMode:"none",steps:[{id:"fabric",code:"fabric_fit",title:"面料与版型",type:"variant"},{id:"jacket",code:"jacket",title:"西服上衣",type:"options"},{id:"trousers",code:"trousers",title:"西裤款式",type:"options"},{id:"measure",code:"measurements",title:"量体尺寸",type:"measurements"},{id:"review",code:"review",title:"配置确认",type:"review"}],measurementFields:[{code:"height",name:"身高",unit:"CM",min:140,max:210,step:1},{code:"weight",name:"体重",unit:"KG",min:40,max:180,step:1},{code:"sleeve_length",name:"袖长",unit:"CM",min:40,max:90,step:.5},{code:"trouser_length",name:"裤长",unit:"CM",min:80,max:130,step:.5},{code:"waist",name:"腰围",unit:"CM",min:50,max:160,step:.5}]};
function normalize(value:unknown):Template{const x=(value&&typeof value==="object"?value:{}) as Partial<Template>,c=(x.config&&typeof x.config==="object"?x.config:{}) as Partial<Config>;return{id:String(x.id||crypto.randomUUID()),code:String(x.code||"invalid_template"),name:String(x.name||"未命名模板"),category:["西服","西裤","衬衫","马甲"].includes(String(x.category))?String(x.category):"西服",status:x.status==="published"?"published":"draft",version:Number.isFinite(Number(x.version))?Number(x.version):1,updatedAt:String(x.updatedAt||""),config:{buttonLabel:typeof c.buttonLabel==="string"?c.buttonLabel:starter.buttonLabel,pricingMode:"none",steps:Array.isArray(c.steps)?c.steps:structuredClone(starter.steps),measurementFields:Array.isArray(c.measurementFields)?c.measurementFields:structuredClone(starter.measurementFields)}}}
async function json(url:string,options?:RequestInit){const r=await fetch(url,options),p=await r.json();if(!r.ok)throw new Error(p.error||"请求失败");return p}

export function ConfigAdmin(){
 const [view,setView]=useState<View>("templates"),[items,setItems]=useState<Template[]>([]),[draft,setDraft]=useState<Template|null>(null),[selected,setSelected]=useState(""),[bindings,setBindings]=useState<Binding[]>([]),[versions,setVersions]=useState<Version[]>([]);
 const [search,setSearch]=useState(""),[tab,setTab]=useState("steps"),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{type:string;text:string}|null>(null),[editingBinding,setEditingBinding]=useState<Binding|null>(null);
 const filtered=useMemo(()=>items.filter(x=>(x.name+x.code).toLowerCase().includes(search.toLowerCase())),[items,search]);
 async function loadTemplates(preferred?:string){const p=await json("/api/templates"),list=(Array.isArray(p.data)?p.data:[]).map(normalize);setItems(list);const id=preferred||selected||list[0]?.id;setSelected(id);setDraft(structuredClone(list.find((x:Template)=>x.id===id)||list[0]||null))}
 async function loadBindings(){const p=await json("/api/products");setBindings(p.data||[])}
 async function loadVersions(id?:string){const templateId=id||selected;if(!templateId){setVersions([]);return}const p=await json(`/api/templates/${templateId}/versions`);setVersions(p.data||[])}
 useEffect(()=>{Promise.all([loadTemplates(),loadBindings()]).catch(e=>setNotice({type:"error",text:e.message}))},[]);
 function choose(x:Template){setSelected(x.id);setDraft(structuredClone(x));setNotice(null)}
 async function run(work:()=>Promise<void>,success:string){setBusy(true);setNotice(null);try{await work();setNotice({type:"success",text:success})}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"操作失败"})}finally{setBusy(false)}}
 async function save(publish=false){if(!draft)return;await run(async()=>{const p=await json(`/api/templates/${draft.id}${publish?"/publish":""}`,{method:publish?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});await loadTemplates(draft.id);if(publish)await loadVersions(draft.id)},publish?"模板已发布":"草稿已保存")}
 async function create(source?:Template){await run(async()=>{const p=await json("/api/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:source?`${source.name}（副本）`:"新定制模板",category:source?.category||"西服",config:source?.config||starter})});await loadTemplates(p.data.id)},source?"模板已复制":"模板已创建")}
 async function removeTemplate(){if(!draft||!confirm(`确认删除“${draft.name}”及其发布版本和商品绑定？`))return;await run(async()=>{await json(`/api/templates/${draft.id}`,{method:"DELETE"});setSelected("");await Promise.all([loadTemplates(),loadBindings()])},"模板已删除")}
 function updateStep(i:number,key:keyof Step,value:string|boolean){if(!draft)return;const n=structuredClone(draft);(n.config.steps[i] as unknown as Record<string,unknown>)[key]=key==="required"?value===true||value==="true":value;setDraft(n)}
 function addStep(){if(!draft)return;const n=structuredClone(draft);n.config.steps.push({id:crypto.randomUUID(),code:`step_${n.config.steps.length+1}`,title:"新步骤",type:"options",required:true,options:[]});setDraft(n)}
 function removeStep(i:number){if(!draft)return;const n=structuredClone(draft);n.config.steps.splice(i,1);setDraft(n)}
 function addChoice(stepIndex:number){if(!draft)return;const n=structuredClone(draft),step=n.config.steps[stepIndex];step.options=step.options||[];step.options.push({value:`option_${step.options.length+1}`,label:"新选项"});setDraft(n)}
 function updateChoice(stepIndex:number,optionIndex:number,key:keyof Choice,value:string){if(!draft)return;const n=structuredClone(draft);const option=n.config.steps[stepIndex].options?.[optionIndex];if(option)option[key]=value;setDraft(n)}
 function removeChoice(stepIndex:number,optionIndex:number){if(!draft)return;const n=structuredClone(draft);n.config.steps[stepIndex].options?.splice(optionIndex,1);setDraft(n)}
 function addMeasure(){if(!draft)return;const n=structuredClone(draft);n.config.measurementFields.push({code:`field_${n.config.measurementFields.length+1}`,name:"新尺寸",unit:"CM",min:0,max:200,step:.5});setDraft(n)}
 function updateMeasure(i:number,key:keyof Measure,value:string){if(!draft)return;const n=structuredClone(draft);(n.config.measurementFields[i] as any)[key]=["min","max","step"].includes(key)?Number(value):value;setDraft(n)}
 function removeMeasure(i:number){if(!draft)return;const n=structuredClone(draft);n.config.measurementFields.splice(i,1);setDraft(n)}
 function newBinding(){setEditingBinding({id:"",shopifyProductId:"",productTitle:"",productHandle:"",templateId:items[0]?.id||"",publishedVersion:null})}
 async function saveBinding(){if(!editingBinding)return;await run(async()=>{await json(editingBinding.id?`/api/products/${editingBinding.id}`:"/api/products",{method:editingBinding.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editingBinding)});setEditingBinding(null);await loadBindings()},editingBinding.id?"商品绑定已更新":"商品绑定已创建")}
 async function removeBinding(x:Binding){if(!confirm(`确认解除“${x.productTitle}”的模板绑定？`))return;await run(async()=>{await json(`/api/products/${x.id}`,{method:"DELETE"});await loadBindings()},"商品绑定已删除")}
 function navigate(next:View){setView(next);setNotice(null);if(next==="products")void loadBindings();if(next==="versions")void loadVersions()}
 const published=items.filter(x=>x.status==="published").length;
 return <div className="shell"><aside className="side"><div className="brand"><span className="mark">M</span><div><strong>MTM Studio</strong><small>定制配置中心</small></div></div><nav className="nav"><button className={view==="templates"?"active":""} onClick={()=>navigate("templates")}><span>▦　定制模板</span></button><button className={view==="products"?"active":""} onClick={()=>navigate("products")}><span>◇　商品绑定</span></button><button className={view==="versions"?"active":""} onClick={()=>navigate("versions")}><span>◫　发布记录</span></button></nav><div className="foot">Shopify Mock Admin<br/>Cloudflare Worker + D1</div></aside><main className="main"><header className="top"><h1>配置管理</h1><span className="env">● POC 环境</span></header><div className="content">{notice&&<div className={`notice ${notice.type}`}>{notice.text}</div>}
 {view==="templates"&&<><div className="head"><div><p className="eyebrow">Customization workspace</p><h2>服装定制模板</h2><p>维护步骤、量体规则并发布给 Shopify 商品定制器。</p></div><button className="primary" disabled={busy} onClick={()=>create()}>＋ 新建模板</button></div><section className="stats"><div className="stat"><span>模板总数</span><strong>{items.length}</strong></div><div className="stat"><span>已发布</span><strong>{published}</strong></div><div className="stat"><span>草稿</span><strong>{items.length-published}</strong></div><div className="stat"><span>关联商品</span><strong>{bindings.length}</strong></div></section><div className="work"><section className="panel"><div className="panel-title">模板列表</div><div className="search-wrap"><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索模板名称或编码"/></div><div className="list">{filtered.map(x=><button key={x.id} className={`card ${x.id===selected?"active":""}`} onClick={()=>choose(x)}><strong>{x.name}<span className={`badge ${x.status}`}>{x.status==="published"?"已发布":"草稿"}</span></strong><small>{x.code} · v{x.version} · {x.category}</small></button>)}</div></section><section className="panel">{!draft?<div className="empty">暂无模板，请新建</div>:<div className="editor"><div className="editor-head"><div><h3>{draft.name}</h3><p>{draft.code} · 当前版本 v{draft.version}</p></div><div className="actions"><button className="secondary" onClick={()=>create(draft)}>复制</button><button className="danger" onClick={removeTemplate}>删除</button><button className="secondary" disabled={busy} onClick={()=>save()}>保存草稿</button><button className="primary" disabled={busy} onClick={()=>save(true)}>校验并发布</button></div></div><div className="form"><Field label="模板名称"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="适用品类"><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option>西服</option><option>西裤</option><option>衬衫</option><option>马甲</option></select></Field><Field label="模板编码"><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></Field><Field label="前台按钮文字"><input value={draft.config.buttonLabel} onChange={e=>setDraft({...draft,config:{...draft.config,buttonLabel:e.target.value}})}/></Field></div><div className="tabs"><button className={tab==="steps"?"active":""} onClick={()=>setTab("steps")}>定制步骤</button><button className={tab==="measures"?"active":""} onClick={()=>setTab("measures")}>量体字段</button><button className={tab==="json"?"active":""} onClick={()=>setTab("json")}>JSON 预览</button></div>
 {tab==="steps"&&<><Section title="步骤 CRUD" action={<button className="secondary" onClick={addStep}>＋ 添加步骤</button>}/><div className="steps">{draft.config.steps.map((s,i)=><div className="step" key={s.id}><div className="step-row"><span className="num">{i+1}</span><input value={s.title} onChange={e=>updateStep(i,"title",e.target.value)}/><select value={s.type} onChange={e=>updateStep(i,"type",e.target.value)}><option value="variant">SKU 选择</option><option value="options">定制选项</option><option value="measurements">量体尺寸</option><option value="review">Review</option></select><button className="delete" onClick={()=>removeStep(i)}>删除</button></div><input className="code-input" value={s.code} onChange={e=>updateStep(i,"code",e.target.value)} aria-label="步骤编码"/>{s.type==="options"&&<div className="choice-editor"><div className="choice-head"><strong>候选项</strong><label><input type="checkbox" checked={s.required!==false} onChange={e=>updateStep(i,"required",String(e.target.checked) as never)}/> 必选</label><button className="secondary" onClick={()=>addChoice(i)}>＋ 添加选项</button></div>{(s.options||[]).map((o,j)=><div className="choice-row" key={`${o.value}-${j}`}><input value={o.label} onChange={e=>updateChoice(i,j,"label",e.target.value)} placeholder="显示名称，如藏青色" aria-label="选项名称"/><input value={o.value} onChange={e=>updateChoice(i,j,"value",e.target.value)} placeholder="编码，如 navy" aria-label="选项编码"/><input value={o.image||""} onChange={e=>updateChoice(i,j,"image",e.target.value)} placeholder="图片 URL（可选）" aria-label="选项图片"/><button className="delete" onClick={()=>removeChoice(i,j)}>删除</button></div>)}{!(s.options||[]).length&&<p className="choice-empty">暂无候选项，请点击“添加选项”。</p>}</div>}</div>)}</div></>}
 {tab==="measures"&&<><Section title="量体字段 CRUD" action={<button className="secondary" onClick={addMeasure}>＋ 添加字段</button>}/><div className="steps">{draft.config.measurementFields.map((f,i)=><div className="measure-row" key={`${f.code}-${i}`}><input value={f.name} onChange={e=>updateMeasure(i,"name",e.target.value)} aria-label="字段名称"/><input value={f.code} onChange={e=>updateMeasure(i,"code",e.target.value)} aria-label="字段编码"/><select value={f.unit} onChange={e=>updateMeasure(i,"unit",e.target.value)}><option>CM</option><option>IN</option><option>KG</option></select><input type="number" value={f.min} onChange={e=>updateMeasure(i,"min",e.target.value)} aria-label="最小值"/><input type="number" value={f.max} onChange={e=>updateMeasure(i,"max",e.target.value)} aria-label="最大值"/><input type="number" step="0.1" value={f.step} onChange={e=>updateMeasure(i,"step",e.target.value)} aria-label="步进"/><button className="delete" onClick={()=>removeMeasure(i)}>删除</button></div>)}</div></>}
 {tab==="json"&&<><Section title="前台发布快照"/><pre className="json">{JSON.stringify({templateId:draft.code,version:draft.version,productId:"10296845205799",...draft.config},null,2)}</pre></>}</div>}</section></div></>}
 {view==="products"&&<><div className="head"><div><p className="eyebrow">Product bindings</p><h2>商品绑定</h2><p>将 Shopify Product ID 关联到已配置模板。</p></div><button className="primary" onClick={newBinding}>＋ 新建绑定</button></div>{editingBinding&&<div className="panel binding-form"><div className="form"><Field label="Shopify Product ID"><input value={editingBinding.shopifyProductId} onChange={e=>setEditingBinding({...editingBinding,shopifyProductId:e.target.value})}/></Field><Field label="商品标题"><input value={editingBinding.productTitle} onChange={e=>setEditingBinding({...editingBinding,productTitle:e.target.value})}/></Field><Field label="Handle"><input value={editingBinding.productHandle} onChange={e=>setEditingBinding({...editingBinding,productHandle:e.target.value})}/></Field><Field label="配置模板"><select value={editingBinding.templateId} onChange={e=>setEditingBinding({...editingBinding,templateId:e.target.value})}>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div><div className="actions"><button className="secondary" onClick={()=>setEditingBinding(null)}>取消</button><button className="primary" onClick={saveBinding}>保存绑定</button></div></div>}<div className="panel table-wrap"><table><thead><tr><th>商品</th><th>Product ID</th><th>模板</th><th>版本</th><th>操作</th></tr></thead><tbody>{bindings.map(x=><tr key={x.id}><td><strong>{x.productTitle}</strong><small>{x.productHandle}</small></td><td>{x.shopifyProductId}</td><td>{items.find(t=>t.id===x.templateId)?.name||x.templateId}</td><td>v{x.publishedVersion||"—"}</td><td><button className="link" onClick={()=>setEditingBinding(x)}>编辑</button><button className="link danger-text" onClick={()=>removeBinding(x)}>删除</button></td></tr>)}</tbody></table></div></>}
 {view==="versions"&&<><div className="head"><div><p className="eyebrow">Publish history</p><h2>发布记录</h2><p>查看每次发布生成的不可变配置快照。</p></div><select className="template-select" value={selected} onChange={e=>{setSelected(e.target.value);void loadVersions(e.target.value)}}>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="panel table-wrap"><table><thead><tr><th>版本</th><th>模板</th><th>步骤数</th><th>量体字段</th><th>发布时间</th></tr></thead><tbody>{versions.map(x=><tr key={x.id}><td><strong>v{x.version}</strong></td><td>{items.find(t=>t.id===x.templateId)?.name||x.templateId}</td><td>{x.config.steps?.length||0}</td><td>{x.config.measurementFields?.length||0}</td><td>{new Date(x.publishedAt).toLocaleString("zh-CN")}</td></tr>)}</tbody></table>{!versions.length&&<div className="empty">暂无发布记录</div>}</div></>}</div></main></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Section({title,action}:{title:string;action?:React.ReactNode}){return <div className="section-title"><h4>{title}</h4>{action}</div>}
