"use client";
import { useEffect, useMemo, useState } from "react";

type Step={id:string;code:string;title:string;type:string};
type Measure={code:string;name:string;unit:string;min:number;max:number;step:number};
type Config={buttonLabel:string;pricingMode:"none";steps:Step[];measurementFields:Measure[]};
type Template={id:string;code:string;name:string;category:string;status:"draft"|"published";version:number;config:Config;updatedAt:string};

const starter:Config={buttonLabel:"开始定制",pricingMode:"none",steps:[
  {id:"fabric",code:"fabric_fit",title:"面料与版型",type:"variant"},{id:"jacket",code:"jacket",title:"西服上衣",type:"options"},{id:"trousers",code:"trousers",title:"西裤款式",type:"options"},{id:"measure",code:"measurements",title:"量体尺寸",type:"measurements"},{id:"review",code:"review",title:"配置确认",type:"review"}],measurementFields:[
  {code:"height",name:"身高",unit:"CM",min:140,max:210,step:1},{code:"weight",name:"体重",unit:"KG",min:40,max:180,step:1},{code:"sleeve_length",name:"袖长",unit:"CM",min:40,max:90,step:.5},{code:"trouser_length",name:"裤长",unit:"CM",min:80,max:130,step:.5},{code:"waist",name:"腰围",unit:"CM",min:50,max:160,step:.5}]};

export function ConfigAdmin(){
 const [items,setItems]=useState<Template[]>([]),[draft,setDraft]=useState<Template|null>(null),[selected,setSelected]=useState("");
 const [search,setSearch]=useState(""),[tab,setTab]=useState("steps"),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{type:string;text:string}|null>(null);
 const filtered=useMemo(()=>items.filter(x=>(x.name+x.code).toLowerCase().includes(search.toLowerCase())),[items,search]);
 async function load(preferred?:string){try{const r=await fetch("/api/templates");const p=await r.json();if(!r.ok)throw new Error(p.error);setItems(p.data);const id=preferred||selected||p.data[0]?.id;setSelected(id);setDraft(structuredClone(p.data.find((x:Template)=>x.id===id)||p.data[0]||null))}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"配置服务不可用"})}}
 useEffect(()=>{void load()},[]);
 function choose(x:Template){setSelected(x.id);setDraft(structuredClone(x));setNotice(null)}
 async function save(publish=false){if(!draft)return;setBusy(true);try{const r=await fetch(`/api/templates/${draft.id}${publish?"/publish":""}`,{method:publish?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const p=await r.json();if(!r.ok)throw new Error(p.error);await load(draft.id);setNotice({type:"success",text:publish?`版本 ${p.data.version} 已发布`:"草稿已保存"})}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"保存失败"})}finally{setBusy(false)}}
 async function create(){setBusy(true);try{const r=await fetch("/api/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"新定制模板",category:"西服",config:starter})});const p=await r.json();if(!r.ok)throw new Error(p.error);await load(p.data.id)}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"创建失败"})}finally{setBusy(false)}}
 function updateStep(i:number,key:keyof Step,value:string){if(!draft)return;const n=structuredClone(draft);n.config.steps[i][key]=value;setDraft(n)}
 function addStep(){if(!draft)return;const n=structuredClone(draft);n.config.steps.push({id:crypto.randomUUID(),code:`step_${n.config.steps.length+1}`,title:"新步骤",type:"options"});setDraft(n)}
 function removeStep(i:number){if(!draft)return;const n=structuredClone(draft);n.config.steps.splice(i,1);setDraft(n)}
 const published=items.filter(x=>x.status==="published").length;
 return <div className="shell"><aside className="side"><div className="brand"><span className="mark">M</span><div><strong>MTM Studio</strong><small>定制配置中心</small></div></div><nav className="nav"><button className="active"><span>▦　定制模板</span></button><button><span>◇　商品绑定</span></button><button><span>◫　发布记录</span></button><button><span>⚙　系统设置</span></button></nav><div className="foot">Shopify Mock Admin<br/>Cloudflare Worker + D1</div></aside>
 <main className="main"><header className="top"><h1>配置管理</h1><span className="env">● POC 环境</span></header><div className="content">
 <div className="head"><div><p className="eyebrow">Customization workspace</p><h2>服装定制模板</h2><p>维护步骤、量体规则并发布给 Shopify 商品定制器。</p></div><button className="primary" disabled={busy} onClick={create}>＋ 新建模板</button></div>
 <section className="stats"><div className="stat"><span>模板总数</span><strong>{items.length}</strong></div><div className="stat"><span>已发布</span><strong>{published}</strong></div><div className="stat"><span>草稿</span><strong>{items.length-published}</strong></div><div className="stat"><span>关联商品</span><strong>1</strong></div></section>
 {notice&&<div className={`notice ${notice.type}`}>{notice.text}</div>}<div className="work"><section className="panel"><div className="panel-title">模板列表</div><div className="search-wrap"><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索模板名称或编码"/></div><div className="list">{filtered.map(x=><button key={x.id} className={`card ${x.id===selected?"active":""}`} onClick={()=>choose(x)}><strong>{x.name}<span className={`badge ${x.status}`}>{x.status==="published"?"已发布":"草稿"}</span></strong><small>{x.code} · v{x.version} · {x.category}</small></button>)}</div></section>
 <section className="panel">{!draft?<div className="empty">正在加载模板…</div>:<div className="editor"><div className="editor-head"><div><h3>{draft.name}</h3><p>{draft.code} · 当前版本 v{draft.version}</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>save()}>保存草稿</button><button className="primary" disabled={busy} onClick={()=>save(true)}>校验并发布</button></div></div>
 <div className="form"><div className="field"><label>模板名称</label><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></div><div className="field"><label>适用品类</label><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option>西服</option><option>西裤</option><option>衬衫</option><option>马甲</option></select></div><div className="field"><label>模板编码</label><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></div><div className="field"><label>前台按钮文字</label><input value={draft.config.buttonLabel} onChange={e=>setDraft({...draft,config:{...draft.config,buttonLabel:e.target.value}})}/></div></div>
 <div className="tabs"><button className={tab==="steps"?"active":""} onClick={()=>setTab("steps")}>定制步骤</button><button className={tab==="measures"?"active":""} onClick={()=>setTab("measures")}>量体规则</button><button className={tab==="json"?"active":""} onClick={()=>setTab("json")}>JSON 预览</button></div>
 {tab==="steps"&&<><div className="section-title"><h4>步骤顺序</h4><button className="secondary" onClick={addStep}>＋ 添加步骤</button></div><div className="steps">{draft.config.steps.map((s,i)=><div className="step" key={s.id}><div className="step-row"><span className="num">{i+1}</span><input aria-label={`步骤 ${i+1} 名称`} value={s.title} onChange={e=>updateStep(i,"title",e.target.value)}/><select aria-label={`步骤 ${i+1} 类型`} value={s.type} onChange={e=>updateStep(i,"type",e.target.value)}><option value="variant">SKU 选择</option><option value="options">定制选项</option><option value="measurements">量体尺寸</option><option value="review">Review</option></select><button className="delete" onClick={()=>removeStep(i)}>删除</button></div></div>)}</div></>}
 {tab==="measures"&&<><div className="section-title"><h4>尺寸字段</h4></div><div className="steps">{draft.config.measurementFields.map(f=><div className="step" key={f.code}><strong>{f.name}</strong><div style={{color:"var(--muted)",marginTop:6,fontSize:13}}>{f.code} · {f.min}～{f.max} {f.unit} · 步进 {f.step}</div></div>)}</div></>}
 {tab==="json"&&<><div className="section-title"><h4>前台发布快照</h4></div><pre className="json">{JSON.stringify({templateId:draft.code,version:draft.version,productId:"10296845205799",...draft.config},null,2)}</pre></>}</div>}</section></div></div></main></div>
}
